# API Client consts
API_KEY = "x-api-key"
REFRESH_TOKEN = "refreshToken"

SDK_USER_AGENT = "ElectroluxGroupDeveloperSDK"
SDK_VERSION = "0.1.4"

# Methods
POST = "POST"
GET = "GET"
PUT = "PUT"

AC = "AC"
CA = "CA"
AZUL = "Azul"
BOGONG = "Bogong"
PANTHER = "Panther"
TELICA = "Telica"

FUJI = "Fuji"
MUJU = "Muju"
PUREA9 = "PUREA9"
VERBIER = "Verbier"
WELLA5 = "WELLA5"
WELLA7 = "WELLA7"

SERIES_700 = "700series"
PUREI9 = "PUREi9"
GORDIAS = "Gordias"
CYBELE = "Cybele"

HUSKY = "Husky"
DH = "DH"

OV = "OV"
CR = "CR"
SO = "SO"
DW = "DW"
WD = "WD"
TD = "TD"
WM = "WM"
HD = "HD"
HB = "HB"

DAM_AC = "DAM_AC"

AC_APPLIANCE_TYPE = [AC, CA, BOGONG, PANTHER, AZUL, TELICA]
AP_APPLIANCE_TYPE = [FUJI, MUJU, PUREA9, VERBIER, WELLA5, WELLA7]
DH_APPLIANCE_TYPE = [DH, HUSKY]
RVC_APPLIANCE_TYPE = [SERIES_700, PUREI9, GORDIAS, CYBELE]

APPLIANCE_STATE_OFF = "OFF"
APPLIANCE_STATE_IDLE = "IDLE"
APPLIANCE_STATE_RUNNING = "RUNNING"
APPLIANCE_STATE_PAUSED = "PAUSED"
APPLIANCE_STATE_READY_TO_START = "READY_TO_START"
APPLIANCE_STATE_DELAYED_START = "DELAYED_START"
APPLIANCE_STATE_END_OF_CYCLE = "END_OF_CYCLE"

FAHRENHEIT = "FAHRENHEIT"
CELSIUS = "CELSIUS"

RC_ENABLED = "ENABLED"
RC_NOT_SAFETY_RELEVANT_ENABLED = "NOT_SAFETY_RELEVANT_ENABLED"
RC_DISABLED = "DISABLED"
RC_TEMPORARY_LOCKED = "TEMPORARY_LOCKED"

# Capability and ApplianceState keywords
VALUES = "values"
TYPE = "type"
TYPE_INT = "int"
TYPE_STRING = "string"
REPORTED = "reported"
MAX = "max"
MIN = "min"
STEP = "step"
RANGE = "range"
DISABLED = "disabled"
PROPERTIES = "properties"
